[tool.poetry]
name = "flask-tutorial"
version = "0.1.0"
description = ""
authors = ["Bill Wang <bill.wang>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
